name: SortingHopper2
main: point3d.sortinghopper2.SortingHopper
description: Bukkit plugin that creates item filter from a hopper
version: 2.7
api-version: 1.21
load: POSTWORLD
softdepend:
  - Multiverse-Core
commands:
  sortinghopper:
    description: give | save [name] | load [name] | reload | importminecrafttags
